# Generated by Django 3.2.10 on 2022-02-09 13:20

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yazi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazi',
            name='duzenlenme_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yazi',
            name='olusturulma_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 13, 20, 40, 233188, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yazi',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='resim/yazi'),
        ),
        migrations.AddField(
            model_name='yazi',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2022, 2, 9, 13, 20, 43, 942156, tzinfo=utc), editable=False, max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yazi',
            name='taslak',
            field=models.BooleanField(default=False),
        ),
    ]
